### ISSUE TITLE
遷移先イベントページ(ローカルストレージ)

### ISSUE THREAD

**Issue by Sea10wood** [powaaaaa/techer-me-frontend#33]
![イベントページ_ローカルストレージ](https://github.com/powaaaaa/techer-me-frontend/assets/126382452/ea3989a4-26ab-4249-a223-08cb2ce6b506)

**Comment by Sea10wood** [comment]
イベント登録が済んだときに広場のボタンに変更する仕様

**Comment by powaaaaa** [comment]
エリパラメータで持つことに変更した
