### ISSUE TITLE
TecherME/StickerPreviewのカード作成

### ISSUE THREAD

**Issue by Sea10wood** [powaaaaa/techer-me-frontend#41]
![名刺](https://github.com/powaaaaa/techer-me-frontend/assets/126382452/40d667d0-cff0-4ca0-912d-54f77de5f5b3)

**Comment by Semi-koron** [comment]
こちら思ったのですが下に伸ばすのであれば連絡先(github,X等)の位置とイベントの位置逆の方がよくないでしょうか？

**Comment by Sea10wood** [comment]
CardComponent修正完了。
アイコン移行完了
